### ISSUE TITLE
Error after adding cookies

### ISSUE THREAD

**Issue by Tony-lab-png** [Naguroka/GenshinWidget#1]
After adding the cookies in the settings.ini (I made sure it was accurate) it's saying "Error fetching notes: [10001] Cookies are not valid. Tried logging out and back in to get new tokens but didn't help either.

**Comment by Naguroka** [comment]
Just to confirm, make sure your settings.ini Auth section looks something like this (the X's are for censoring, yours will have random numbers/letters):

[Auth]
ltuid_v2 = XXXXXXXXX
ltoken_v2 = v2_CAISDGM5b3FhcTNzM2dXXXXXXXXXXXXXXXXXXXXXXXXXXEtZjVkNDliNDJiM2E0IN6Jg7EGKNXf-doEMK7N2CRCCXXXXXXXXXX
cookie_token_v2 = v2_CAQSDGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXM2NmYTBkOThhINfQzLQGKImb93Mwrs3YJEILaGs0ZV9nbG9iYWw.VyiTZgAAAAAB.MXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXPDWR0NMpEJ91MoOYBF4CI
account_mid_v2 = 1fXXXXXXXr_hy

**Comment by Naguroka** [comment]
It works fine for me. I grabbed my cookies from Chrome. I don't think it matters what browser you use, but just incase, what browser are you using?

**Comment by Tony-lab-png** [comment]
Yeah it looks the same and I was using Firefox but did try chrome as well. Could it be VPN blocking? That's the only thing I could think of that would prevent it from being able to reach the API

**Comment by Naguroka** [comment]
Possibly? I never tested it with a VPN. However, the cookies should still be valid. Did you make sure none of your Genshin profile is private? You need to make sure all your info is public so the program can grab the info.

**Comment by Tony-lab-png** [comment]
Yeah I double checked everything, hoyolab privacy, redownloaded file and reentered cookies still not working. Weird thing is I've used genshin wizard discord bot before which also requires your cookies and that worked

**Comment by Naguroka** [comment]
I think I possibly found the problem when testing it on a different computer. I used firefox and when grabbing the "ltuid_v2" for the settings.ini file, make sure you are using your actual Genshin Impact UID, not the cookie value called "ltuid_v2". You can get this from the game itself (its the code you give your friends so they can add you). Or you can get from the hoyolab battle chronicle (top left to the right of your server. "UIDXXXXXXXXX")

If that doesn't work, make sure all of your dependencies are updated to their latest versions.

**Comment by Tony-lab-png** [comment]
Using the UID didn't work at first but then when I logged out and back in again it did so I guess it needed the real UID _and_ fresh cookie tokens? Either way it works now so thanks!

**Comment by Naguroka** [comment]
No problem!
